name: Datascraper

on:
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * 1'  # This will run the action every day at 2:15am.


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
      with:
        node-version: '16' # Use Node.js version 16

      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        node-version: '16' # Use Node.js version 16

    - name: Install dependencies
      run: |
        pip install -r BASEscraping/requirements.txt
        
    - name: Run datascraper.py
      run: python BASEscraping/datascraper.py
