name: RunBASEnewsletter

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * 1"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  WebScraping:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip install -r BASEnewsletter/install_packages.txt
      
      - name: Run newsletter
        run:
          python BASEnewsletter/WeeklyNewsletter.py
